### ISSUE TITLE
name "AudienceType"

### ISSUE THREAD

**Issue by philbarker** [stuartasutton/LRMI_Vocabs#3]
I think calling this vocabulary Audience Type will lead to confusion with the schema.org Type Audience http://schema.org/Audience . An aggravating factor is that the values relate to the educationalRole property of EducationalAudience (i.e the Audience Type vocabulary does not relate to a property of the Audience Type). 

I propose the name educational audience role.

**Comment by stuartasutton** [comment]
Sounds good to me.
