### ISSUE TITLE
Won't import into protege. Incorrect prefix on line 51

### ISSUE THREAD

**Issue by philbarker** [stuartasutton/LRMI_Vocabs#4]
I think lrmiType on line 51 should be audType
skos:narrower lrmiType:a6760d5b-97b2-46ab-8b83-80ccd3f789d9;

**Comment by stuartasutton** [comment]
Thanks for catching the error, Phil. I made correction on master (still learning github). Note that in the vocabs Jim pointed us to, the referenced concept is not actually treated as a narrower term...I did that to demo broader/narrower and then did not include the skos:broader...added it to master.

**Comment by philbarker** [comment]
OK Stuart, I created a fork and fixed it there so you have a pull
      request you can ignore.
      
      I'm a github novice, so this is good experience for me.
      
      Phil
      
      On 29/01/15 13:23, Stuart Sutton wrote:
    
    
      
      Thanks for catching the error, Phil. I made correction on
        master (still learning github). Note that in the vocabs Jim
        pointed us to, the referenced concept is not actually treated as
        a narrower term...I did that to demo broader/narrower and then
        did not include the skos:broader...added it to master.
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
          
           
        
        
      
    
    
    
    -- 
--  
Phil Barker           @philbarker
LRMI, Cetis, ICBL     http://people.pjjk.net/phil
Heriot-Watt University

Ubuntu: http://xkcd.com/456/
  not so much an operating system as a learning opportunity.
